name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm ci
        working-directory: projet-startup

      - name: Lint (ESLint)
        run: npm run lint
        working-directory: projet-startup

      - name: Tests unitaires (Jest)
        run: npm test
        working-directory: projet-startup
